project:
  type: website
  output-dir: docs

website:
  title: "Alexander Wen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - walkthrough.qmd
      - sidebar:logs 
      
  sidebar: 
    - id: logs
      title: Journals
      contents:
        - text: Archive
        - href: archive.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



